#!/bin/bash

# Install AWS tools if not present
if [ ! -f /usr/local/bin/aws ]; then
    wget -nv https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
    unzip awscli-bundle.zip
    awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    rm -rf awscli-bundle*
fi

INSTANCE_ID=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/instance-id`
GROUP=`/usr/local/bin/aws ec2 describe-tags --o text --region {{region}} --filters\
  "Name=resource-type,Values=instance"\
  "Name=resource-id,Values=${INSTANCE_ID}"\
  "Name=key,Values=group" | awk '{ print $5 }'`

# Get the IP address and domain names
IPV4=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/local-ipv4`
LDNS=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/local-hostname`
PDNS=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/public-hostname`

# Set the host name
DOMAIN="{{publicDomain}}"
HOST="${GROUP}-${INSTANCE_ID}-{{region}}"
FQDN="${HOST}.$DOMAIN"

hostname ${HOST}

if [ -f /etc/sysconfig/network ]; then
    sed -i "s/HOSTNAME.*/HOSTNAME=${FQDN}/g" /etc/sysconfig/network
else
    echo ${FQDN} > /etc/hostname
fi

# Update hosts file
cat<<HOSTS> /etc/hosts
# This file automatically generated by route53.sh boot script
127.0.0.1 localhost
${IPV4} ${FQDN} ${HOST}
HOSTS

# Update Route53 Public/Private zones
cat<<JSON> /tmp/aws-r53-changes.json
{
    "Changes": [{
        "Action": "UPSERT",
        "ResourceRecordSet": {
            "Name": "${FQDN}.",
            "Type": "CNAME",
            "TTL":  300,
            "ResourceRecords": [{
                "Value": "REPLACE"
            }]
        }
    }]
}
JSON

sed "s/REPLACE/${LDNS}/" /tmp/aws-r53-changes.json > /tmp/aws-r53-private.json
COMMAND="/usr/local/bin/aws route53 change-resource-record-sets --hosted-zone-id {{privateZone}}\
  --change-batch file:///tmp/aws-r53-private.json"
for i in {1..5}; do
   ${COMMAND} && break || sleep $[$i*$i]
done

sed "s/REPLACE/${PDNS}/" /tmp/aws-r53-changes.json > /tmp/aws-r53-public.json
COMMAND="/usr/local/bin/aws route53 change-resource-record-sets --hosted-zone-id {{publicZone}}\
  --change-batch file:///tmp/aws-r53-public.json"
for i in {1..5}; do
   ${COMMAND} && break || sleep $[$i*$i]
done

rm -f /tmp/aws-r53-*.json
